(()=>{
'use strict';
const data=window.APK_PICKER_DATA;if(!data)return;const protocols=(data.protocols||[]).slice().sort((a,b)=>(a.order||0)-(b.order||0));
let activeGroup='All',query='',recommended=new Set();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=$('#pickerSteps'),rail=$('#selectedRail'),result=$('#resultPanel'),related=$('#relatedList'),grid=$('#protocolGrid'),groups=$('#groupFilters'),search=$('#protocolSearch'),count=$('#resultCount'),reset=$('#resetAll'),toast=$('#toast');
function say(t){if(!toast)return;toast.textContent=t;toast.hidden=false;clearTimeout(say.t);say.t=setTimeout(()=>toast.hidden=true,1600)}
function copy(t,msg){if(!navigator.clipboard)return say('Copy is not available here.');navigator.clipboard.writeText(t).then(()=>say(msg)).catch(()=>say('Copy failed.'))}
function pById(id){return protocols.find(p=>p.id===id)}
function tagList(choice){return Array.isArray(choice.tags)?choice.tags:String(choice.tags||'').split(/[|,]/).filter(Boolean)}
function renderSteps(){if(!steps)return;steps.innerHTML=(data.steps||[]).map((s,i)=>`<section class="step-block"><div class="step-number">${i+1}</div><div><h3>${esc(s.title)}</h3><div class="choice-grid">${(s.choices||[]).map(c=>`<button class="choice-button" type="button" aria-pressed="false" data-step="${esc(s.id)}" data-tags="${esc(tagList(c).join('|'))}">${esc(c.label||c[0])}</button>`).join('')}</div></div></section>`).join('')}
function renderGroups(){if(!groups)return;groups.innerHTML=(data.groups||['All']).map(g=>`<button class="group-chip" type="button" aria-pressed="${g==='All'}" data-group-filter="${esc(g)}">${esc(g)}</button>`).join('')}
function choices(){return $$('.choice-button[aria-pressed="true"]').map(b=>({step:b.dataset.step,label:b.textContent.trim(),tags:String(b.dataset.tags||'').split('|').filter(Boolean)}))}
function selectedByStep(){const map={deal:[],off:[],want:[]};choices().forEach(c=>map[c.step]?.push(c.label));return map}
function score(p,cs){let n=0;const sc=data.scoring||{},sw=sc.stepWeights||{};const all=new Set;cs.forEach(c=>c.tags.forEach(t=>all.add(t)));cs.forEach(c=>{const w=sw[c.step]??1,pt=p.primaryTags||[],st=p.secondaryTags||[],at=p.avoidTags||[],it=p.intentTags||[];let part=0;if(c.tags.some(t=>at.includes(t)))part=sc.choiceAvoid??-3.5;else if(c.tags.some(t=>pt.includes(t)))part=sc.choicePrimary??2;else if(c.tags.some(t=>st.includes(t)))part=sc.choiceSecondary??.75;if(c.step==='want'&&c.tags.some(t=>it.includes(t)))part+=sc.intentBonus??1.2;n+=part*w});const ctx=p.contextTags||[];if(ctx.length){const has=ctx.some(t=>all.has(t)),deal=cs.some(c=>c.step==='deal'&&c.tags.some(t=>ctx.includes(t)));if(has)n+=sc.contextBonus??1.1;if(deal)n+=sc.dealContextBonus??1.6;else if(p.contextRequired&&!has)n=(n*(sc.contextSoftCap??.55))+(sc.missingContextPenalty??-1.25)}return n}
function ranked(){const cs=choices();return protocols.map(p=>({p,score:score(p,cs)})).sort((a,b)=>b.score-a.score||(a.p.order||0)-(b.p.order||0))}
function compact(arr){if(!arr.length)return '<em>not chosen yet</em>';return arr.slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')+(arr.length>3?`<span>+${arr.length-3}</span>`:'')}
function renderRail(){if(!rail)return;const m=selectedByStep();rail.innerHTML=`<div class="rail-lane"><strong>have</strong><div class="rail-tags">${compact(m.deal)}</div></div><div class="rail-lane"><strong>friction</strong><div class="rail-tags">${compact(m.off)}</div></div><div class="rail-lane"><strong>shift</strong><div class="rail-tags">${compact(m.want)}</div></div>`}
function actionSet(p,label='Open'){return `<a class="action action-primary" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a><button class="action" type="button" data-copy-protocol="${esc(p.id)}">Copy protocol</button><button class="action" type="button" data-copy-instructions="${esc(p.id)}">Copy instructions</button>`}
function relatedFor(best,rank){const ids=[];(best.companions||[]).forEach(id=>ids.push(id));rank.filter(e=>e.p.id!==best.id&&e.score>0).slice(0,5).forEach(e=>ids.push(e.p.id));return [...new Set(ids)].map(pById).filter(Boolean).slice(0,3)}
function renderRelated(list){if(!related)return;if(!list.length){related.innerHTML='';return}related.innerHTML=list.map(p=>`<article class="related-card"><div><h4>${esc(p.title)}</h4><p>${esc(p.category)}</p></div><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Open</a></article>`).join('')}
function renderResult(){renderRail();const cs=choices(),rank=ranked();recommended=new Set;if(!cs.length){result.innerHTML=`<p class="empty-result">${esc(data.uiCopy?.emptyResult||'Choose a few signals. The path will appear here.')}</p>`;renderRelated([]);highlight();return}const best=rank[0];if(!best||best.score<=0){result.innerHTML=`<p class="empty-result">${esc(data.uiCopy?.noMatch||'This kit may not cover the whole job.')}</p>`;renderRelated([]);highlight();return}const close=rank[1]&&best.score-rank[1].score <= (data.scoring?.tieMargin||1.25),label=close?'Possible starting point':'Use now';const extras=relatedFor(best.p,rank);recommended.add(best.p.id);extras.forEach(p=>recommended.add(p.id));result.innerHTML=`<div><p class="result-label">${esc(label)}</p><h3 class="result-title">${esc(best.p.title)}</h3><p class="result-copy">${esc(best.p.shortDescription)}</p></div><div class="result-actions">${actionSet(best.p,'Open')}</div><details class="why-toggle"><summary>Why this path</summary><p>${esc(best.p.useWhen)}</p><p><strong>Not for:</strong> ${esc((best.p.notFor||[]).slice(0,2).join('; ')||'nothing obvious from this path')}</p></details>`;renderRelated(extras);highlight()}
function detailBlock(kind,title,itemsOrText){const body=Array.isArray(itemsOrText)?`<ul>${itemsOrText.slice(0,4).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p>${esc(itemsOrText||'')}</p>`;return `<div class="detail-cell detail-${kind}"><h4>${esc(title)}</h4>${body}</div>`}
function indexRow(p){const searchText=[p.title,p.group,p.category,p.shortDescription,p.useWhen,(Array.isArray(p.searchKeywords)?p.searchKeywords.join(' '):p.searchKeywords||'')].join(' ').toLowerCase();return `<article class="protocol-item" data-protocol-id="${esc(p.id)}" data-group="${esc(p.group)}" data-search="${esc(searchText)}"><div class="item-main"><div class="row-meta"><span>${esc(p.group)}</span><span>${esc(p.category)}</span></div><h3 class="row-title">${esc(p.title)}</h3><p class="row-desc">${esc(p.shortDescription)}</p></div><div class="row-actions"><a class="action action-primary" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Open</a></div><details class="row-details"><summary class="detail-trigger"><span></span></summary><div class="detail-actions"><button class="action" type="button" data-copy-protocol="${esc(p.id)}">Copy protocol</button><button class="action" type="button" data-copy-instructions="${esc(p.id)}">Copy instructions</button></div><div class="detail-grid">${detailBlock('best','Best for',p.bestFor||[])}${detailBlock('needs','Needs',p.needs||[])}${detailBlock('warn','Not for',p.notFor||[])}${detailBlock('out','Output',p.outputMode||'')}</div></details></article>`}
function renderIndex(){if(!grid)return;grid.innerHTML=protocols.map(indexRow).join('');filterIndex()}
function filterIndex(){let n=0;const q=query.trim().toLowerCase();$$('#protocolGrid .protocol-item').forEach(r=>{const show=(activeGroup==='All'||r.dataset.group===activeGroup)&&(!q||(r.dataset.search||'').includes(q));r.hidden=!show;if(show)n++});if(count)count.textContent=`${n} ${n===1?'protocol':'protocols'}`;highlight()}
function highlight(){$$('#protocolGrid .protocol-item').forEach(r=>r.classList.toggle('is-recommended',recommended.has(r.dataset.protocolId)))}
function copyInstructions(id){const p=pById(id);if(!p)return;copy(`${data.copyInstruction}\n\nProtocol: ${p.title}\nURL: ${p.url}`,'Instructions copied.')}
function copyProtocol(id){const p=pById(id);if(!p)return;say('Copying protocol…');fetch(p.rawUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.text()}).then(t=>copy(t,'Protocol copied.')).catch(()=>say('Could not copy the protocol. Open it manually.'))}
document.addEventListener('click',e=>{const t=e.target;if(!(t instanceof Element))return;const ch=t.closest('.choice-button');if(ch){const on=ch.getAttribute('aria-pressed')!=='true';ch.setAttribute('aria-pressed',on?'true':'false');renderResult();return}const chip=t.closest('[data-group-filter]');if(chip){activeGroup=chip.dataset.groupFilter||'All';$$('[data-group-filter]').forEach(b=>b.setAttribute('aria-pressed',b===chip?'true':'false'));filterIndex();return}const cp=t.closest('[data-copy-protocol]');if(cp)return copyProtocol(cp.dataset.copyProtocol);const ci=t.closest('[data-copy-instructions]');if(ci)return copyInstructions(ci.dataset.copyInstructions)});
search?.addEventListener('input',()=>{query=search.value||'';filterIndex()});
reset?.addEventListener('click',()=>{$$('.choice-button').forEach(b=>b.setAttribute('aria-pressed','false'));activeGroup='All';query='';if(search)search.value='';$$('[data-group-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.groupFilter==='All'?'true':'false'));recommended=new Set();renderResult();filterIndex();say('Reset.')});
renderSteps();renderGroups();renderIndex();renderResult();
})();
