(()=>{
"use strict";
const data=window.APK_PICKER_DATA;if(!data)return;const protocols=data.protocols||[];let activeGroup="All",query="",recommended=new Set();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);
const toast=$("#toast"),result=$("#resultPanel"),grid=$("#protocolGrid"),steps=$("#pickerSteps"),groups=$("#groupFilters"),search=$("#protocolSearch"),count=$("#resultCount"),reset=$("#resetAll");
function say(t){if(!toast)return;toast.textContent=t;toast.hidden=false;clearTimeout(say.t);say.t=setTimeout(()=>toast.hidden=true,1800)}
function copy(t,msg){if(!navigator.clipboard)return say("Copy is not available here.");navigator.clipboard.writeText(t).then(()=>say(msg)).catch(()=>say("Copy failed."))}
function protocol(id){return protocols.find(p=>p.id===id)}
function selectedTags(){const tags=new Set;$$('.choice-button[aria-pressed="true"]').forEach(b=>String(b.dataset.tags||"").split(',').filter(Boolean).forEach(t=>tags.add(t)));return tags}
function selectedText(){const by={};$$('.choice-button[aria-pressed="true"]').forEach(b=>{(by[b.dataset.step]??=[]).push(b.textContent.trim())});const out=[];if(by.deal)out.push(`You are dealing with ${by.deal.join(", ")}.`);if(by.off)out.push(`What feels off: ${by.off.join(", ")}.`);if(by.want)out.push(`You want to ${by.want.join(", ")}.`);return out.join(" ")}
function score(p,tags){let n=0;tags.forEach(t=>{if((p.primaryTags||[]).includes(t))n+=data.scoring.primary;if((p.secondaryTags||[]).includes(t))n+=data.scoring.secondary;if((p.avoidTags||[]).includes(t))n+=data.scoring.avoid});return n}
function ranked(){const tags=selectedTags();return protocols.map(p=>({p,score:score(p,tags)})).sort((a,b)=>b.score-a.score||a.p.order-b.p.order)}
function renderSteps(){if(!steps)return;steps.innerHTML=(data.steps||[]).map((s,i)=>`<section class="picker-step"><p class="step-kicker">Step ${i+1}</p><h3>${esc(s.title)}</h3><div class="choice-grid">${s.choices.map(c=>`<button class="choice-button" type="button" aria-pressed="false" data-step="${esc(s.id)}" data-tags="${esc(c[1])}">${esc(c[0])}</button>`).join("")}</div></section>`).join("")}
function renderGroups(){if(!groups)return;groups.innerHTML=(data.groups||["All"]).map(g=>`<button class="group-chip" type="button" aria-pressed="${g==="All"}" data-group-filter="${esc(g)}">${esc(g)}</button>`).join("")}
function card(p){return `<article class="protocol-card" data-protocol-id="${esc(p.id)}" data-group="${esc(p.group)}" data-search="${esc([p.title,p.group,p.category,p.shortDescription,p.useWhen,p.searchKeywords].join(' ').toLowerCase())}"><div class="card-topline"><span class="group-badge">${esc(p.group)}</span><span class="category-label">${esc(p.category)}</span></div><h3>${esc(p.title)}</h3><p class="card-description">${esc(p.shortDescription)}</p><p class="use-when">${esc(p.useWhen)}</p><div class="card-actions"><a class="button button-primary" href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Open protocol</a><button class="button" type="button" data-copy-protocol="${esc(p.id)}">Copy protocol</button><button class="button" type="button" data-copy-instructions="${esc(p.id)}">Copy instructions</button></div><details class="card-details"><summary>Details</summary><div class="details-grid"><div><h4>Best for</h4><ul>${(p.bestFor||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><h4>Not for</h4><ul>${(p.notFor||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><h4>Needs</h4><ul>${(p.needs||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><h4>Output mode</h4><p>${esc(p.outputMode||"")}</p></div></div></details></article>`}
function renderCards(){if(!grid)return;grid.innerHTML=protocols.sort((a,b)=>a.order-b.order).map(card).join("");filterCards()}
function also(best,rank){const ids=new Set(best.companions||[]);rank.slice(1,6).forEach(e=>{if(e.score>0)ids.add(e.p.id)});ids.delete(best.id);return [...ids].map(protocol).filter(Boolean).slice(0,3)}
function renderResult(){if(!result)return;const tags=selectedTags();recommended=new Set;if(!tags.size){result.innerHTML=`<p class="muted">${esc(data.uiCopy.emptyResult)}</p>`;highlight();return}const rank=ranked(),best=rank[0];if(!best||best.score<=0){result.innerHTML=`<p class="muted">${esc(data.uiCopy.noMatch)}</p>`;highlight();return}const label=best.score>=(data.scoring.weakThreshold||3)?"Best match":"Closest useful match",extra=also(best.p,rank);recommended.add(best.p.id);extra.forEach(p=>recommended.add(p.id));result.innerHTML=`<p class="muted">${esc(selectedText()||data.uiCopy.partialResult)}</p><div class="result-card"><p class="small-label">${label}</p><h4>${esc(best.p.title)}</h4><p>${esc(best.p.shortDescription)}</p><p class="muted"><strong>Why this fits:</strong> ${esc(best.p.useWhen)}</p><p class="muted"><strong>When not to use it:</strong> ${esc((best.p.notFor||[]).slice(0,2).join('; '))}</p><div class="result-actions"><a class="button button-primary" href="${esc(best.p.url)}" target="_blank" rel="noopener noreferrer">Open protocol</a><button class="button" type="button" data-copy-instructions="${esc(best.p.id)}">Copy instructions</button></div></div>${extra.length?`<div class="result-card"><p class="small-label">Also useful</p><ul class="result-list">${extra.map(p=>`<li><strong>${esc(p.title)}</strong><br><span class="muted">${esc(p.shortDescription)}</span></li>`).join("")}</ul></div>`:""}`;highlight()}
function highlight(){$$('.protocol-card').forEach(c=>c.classList.toggle('is-recommended',recommended.has(c.dataset.protocolId)))}
function filterCards(){let visible=0;const q=query.trim().toLowerCase();$$('.protocol-card').forEach(c=>{const okGroup=activeGroup==='All'||c.dataset.group===activeGroup,okSearch=!q||(c.dataset.search||'').includes(q),show=okGroup&&okSearch;c.hidden=!show;if(show)visible++});if(count)count.textContent=`${visible} ${visible===1?'protocol':'protocols'}`}
function copyInstructions(id){const p=protocol(id);if(!p)return;copy(`${data.copyInstruction}\n\nProtocol: ${p.title}\nURL: ${p.url}`,'Instructions copied.')}
function copyProtocol(id){const p=protocol(id);if(!p)return;say('Copying protocol…');fetch(p.rawUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.text()}).then(t=>copy(t,'Protocol copied.')).catch(()=>say('Could not copy the protocol. Open it manually.'))}
document.addEventListener('click',e=>{const t=e.target;if(!(t instanceof Element))return;const ch=t.closest('.choice-button');if(ch){ch.setAttribute('aria-pressed',ch.getAttribute('aria-pressed')==='true'?'false':'true');renderResult();return}const g=t.closest('[data-group-filter]');if(g){activeGroup=g.dataset.groupFilter||'All';$$('[data-group-filter]').forEach(b=>b.setAttribute('aria-pressed',b===g?'true':'false'));filterCards();return}const ci=t.closest('[data-copy-instructions]');if(ci)return copyInstructions(ci.dataset.copyInstructions);const cp=t.closest('[data-copy-protocol]');if(cp)return copyProtocol(cp.dataset.copyProtocol)});
if(search)search.addEventListener('input',()=>{query=search.value||'';filterCards()});
if(reset)reset.addEventListener('click',()=>{$$('.choice-button').forEach(b=>b.setAttribute('aria-pressed','false'));activeGroup='All';query='';if(search)search.value='';$$('[data-group-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.groupFilter==='All'?'true':'false'));recommended=new Set;renderResult();filterCards();say('Reset.')});
renderSteps();renderGroups();renderCards();renderResult();
})();
